# Generated by Django 5.2.3 on 2025-06-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notification', max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('debate_message', 'New Debate Message'), ('debate_invite', 'Debate Invitation'), ('debate_result', 'Debate Result'), ('achievement', 'Achievement'), ('system', 'System Notification'), ('moderation', 'Moderation Action')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
