# Generated by Django 5.2.3 on 2025-06-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('debate_message', 'New Debate Message'), ('debate_invite', 'Debate Invitation'), ('debate_result', 'Debate Result'), ('achievement', 'Achievement'), ('system', 'System Notification'), ('moderation', 'Moderation Action')], default='system', max_length=20),
        ),
    ]
