# Generated by Django 5.2.3 on 2025-06-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_notifications_enabled_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether user receives notifications (always True for debate messages)'),
        ),
    ]
