# Generated by Django 5.2.3 on 2025-06-22 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debatesession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debatetopic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debatesession',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='debates.debatetopic'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='debates.debatesession'),
        ),
        migrations.AddField(
            model_name='onlineparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_participants', to='debates.debatesession'),
        ),
        migrations.AddField(
            model_name='onlineparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='debates.debatesession'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_users', to='debates.debatesession'),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='debatetopic',
            index=models.Index(fields=['created_at'], name='debates_deb_created_15d190_idx'),
        ),
        migrations.AddIndex(
            model_name='debatetopic',
            index=models.Index(fields=['is_active'], name='debates_deb_is_acti_8c9888_idx'),
        ),
        migrations.AddIndex(
            model_name='debatesession',
            index=models.Index(fields=['start_time'], name='debates_deb_start_t_8c43e8_idx'),
        ),
        migrations.AddIndex(
            model_name='debatesession',
            index=models.Index(fields=['is_active'], name='debates_deb_is_acti_c41a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='debates_mes_timesta_526494_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'timestamp'], name='debates_mes_session_4c5a38_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineparticipant',
            index=models.Index(fields=['session', 'connected_at'], name='debates_onl_session_ea515f_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineparticipant',
            index=models.Index(fields=['last_seen'], name='debates_onl_last_se_23d418_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineparticipant',
            unique_together={('user', 'session')},
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['joined_at'], name='debates_par_joined__4b055b_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_active'], name='debates_par_is_acti_80b557_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'session')},
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['session', 'is_typing'], name='debates_typ_session_14d524_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['updated_at'], name='debates_typ_updated_fd794d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingindicator',
            unique_together={('user', 'session')},
        ),
    ]
